name: pay_roll
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  camera: ^0.10.5+9
  intl: ^0.19.0
  image: ^4.0.15
  http: ^1.2.2
  flutter_neumorphic_plus: ^3.4.0
  calendar_view: ^1.3.0
  slide_to_act: ^2.0.2
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  device_preview: ^1.2.0
  universal_html: ^2.2.4
  device_preview_screenshot: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/adp_logo.png"

  # dart run flutter_launcher_icons:main

flutter_native_splash:
  color: "#FFFFFF"
  # color_dark: "#272727"
  image: assets/images/logo.png
  # image_dark: assets/logos/style-hub-splash-logo-white.png

  android_12:
    color: "#FFFFFF"
    # color_dark: "#272727"
    image: assets/images/logo.png
    # image_dark: assets/logos/style-hub-splash-logo-white.png

  web: true
  image_web: assets/images/logo.png
  branding_web: assets/images/logo.png

  # dart run flutter_native_splash:create --path=pubspec.yaml
  # dart run flutter_native_splash:remove
